import React from "react";
import {
  FaMapMarkerAlt,
  FaEnvelope,
  FaPhoneAlt,
  FaLinkedin,
  FaFacebook,
  FaInstagram,
} from "react-icons/fa";
import logo from "../assets/Home/Frame 1618871548.png";

const Footer = () => {
  return (
    <footer className="bg-second md:rounded-t-[120px] rounded-t-[50px] text-white pt-20 pb-8 px-4 md:px-8">
      <div className="max-w-7xl mx-auto">
        {/* Main Content Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-12 mb-12">
          {/* Left - Circuit Graphic */}
          <div className="flex justify-center lg:justify-start">
            <img
              src={logo}
              alt="Logo"
              className="md:w-[334px] w-[200px] mx-auto"
            />
          </div>

          {/* Center - Description & Links */}
          <div className="text-center lg:text-left">
            <p className="text-lg leading-relaxed mb-8">
              <span className="font-bold">Eco System</span> We assist industry
              and government leaders in developing and deploying these
              technological solutions. These partnerships reflect the body of
              work generated by ECOSYST, driven by the latest tools and
              technologies.
            </p>

            {/* Social Media Icons */}
            <div className="flex justify-center lg:justify-start gap-6 mb-8">
              <a href="https://www.instagram.com/eco.syst/">
                <FaInstagram className="w-8 h-8 text-white hover:text-primary cursor-pointer transition-colors" />
              </a>
              <a href="https://www.linkedin.com/company/ecosyst220/">
                <FaLinkedin className="w-8 h-8 text-white hover:text-primary cursor-pointer transition-colors" />
              </a>
              <a href="https://www.facebook.com/share/16hSNfdLRG/">
                <FaFacebook className="w-8 h-8 text-white hover:text-primary cursor-pointer transition-colors" />
              </a>
            </div>

            {/* Navigation Links */}
            <div className="flex flex-col lg:flex-row justify-center lg:justify-start gap-6">
              <a
                href="#"
                className="text-white underline hover:text-primary transition-colors"
              >
                Portfolio
              </a>
              <a
                href="#"
                className="text-white underline hover:text-primary transition-colors"
              >
                Our Team
              </a>
              <a
                href="#"
                className="text-white underline hover:text-primary transition-colors"
              >
                About Us
              </a>
            </div>
          </div>

          {/* Right - Contacts & Services */}
          <div className="space-y-8">
            {/* Contacts Section */}
            <div>
              <h3 className="text-2xl font-bold mb-4">Contacts</h3>
              <ul className="space-y-3">
                <li className="flex items-start gap-3">
                  <FaMapMarkerAlt className="mt-1 text-primary flex-shrink-0" />
                  <span className="text-sm">Tanta, Egypt</span>
                </li>
                <li className="flex items-start gap-3">
                  <FaEnvelope className="mt-1 text-primary flex-shrink-0" />
                  <span className="text-sm">ecosyt.company@gmail.com</span>
                </li>
                <li className="flex items-start gap-3">
                  <FaPhoneAlt className="mt-1 text-primary flex-shrink-0" />
                  <span className="text-sm">+201044847442</span>
                </li>
              </ul>
            </div>

            {/* Services Section */}
            <div>
              <h3 className="text-2xl font-bold mb-2">Services</h3>
              <h4 className="text-lg font-semibold mb-3">Software Solution</h4>
              <ul className="space-y-2">
                <li>
                  <a
                    href="#"
                    className="text-white underline hover:text-primary transition-colors"
                  >
                    Web App
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="text-white underline hover:text-primary transition-colors"
                  >
                    Mobile App
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="text-white underline hover:text-primary transition-colors"
                  >
                    Desktop App
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>

        {/* Copyright */}
        <div className="text-center pt-8 border-t border-white/20">
          <p className="text-sm text-white">
            © 2025 Eco System. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
